### ISSUE TITLE
WARNING: npm peer requirements not installed:

### ISSUE THREAD

**Issue by hackpiro** [kadirahq/meteor-react-layout#61]
i'm using meteor Meteor 1.4.1.1
i installed the packages but the console log return this 

```
I20160915-17:19:19.749(2)? [Error: Can't find npm module 'react-addons-transition-group/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
I20160915-17:19:19.750(2)? [Error: Can't find npm module 'react-addons-css-transition-group/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
I20160915-17:19:19.751(2)? [Error: Can't find npm module 'react-addons-linked-state-mixin/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
I20160915-17:19:19.752(2)? [Error: Can't find npm module 'react-addons-create-fragment/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
I20160915-17:19:19.753(2)? [Error: Can't find npm module 'react-addons-update/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
I20160915-17:19:19.754(2)? [Error: Can't find npm module 'react-addons-pure-render-mixin/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
I20160915-17:19:19.754(2)? [Error: Can't find npm module 'react-addons-test-utils/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
I20160915-17:19:19.755(2)? [Error: Can't find npm module 'react-addons-perf/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
W20160915-17:19:19.756(2)? (STDERR) WARNING: npm peer requirements not installed:
W20160915-17:19:19.757(2)? (STDERR)  - react@15.3.1 installed, react@0.14.x needed
W20160915-17:19:19.757(2)? (STDERR)  - react-dom@15.3.1 installed, react-dom@0.14.x needed
W20160915-17:19:19.757(2)? (STDERR)  - react-addons-transition-group@0.14.x not installed.
W20160915-17:19:19.757(2)? (STDERR)  - react-addons-css-transition-group@0.14.x not installed.
W20160915-17:19:19.758(2)? (STDERR)  - react-addons-linked-state-mixin@0.14.x not installed.
W20160915-17:19:19.759(2)? (STDERR)  - react-addons-create-fragment@0.14.x not installed.
W20160915-17:19:19.759(2)? (STDERR)  - react-addons-update@0.14.x not installed.
W20160915-17:19:19.759(2)? (STDERR)  - react-addons-pure-render-mixin@0.14.x not installed.
W20160915-17:19:19.760(2)? (STDERR)  - react-addons-test-utils@0.14.x not installed.
W20160915-17:19:19.760(2)? (STDERR)  - react-addons-perf@0.14.x not installed.
W20160915-17:19:19.760(2)? (STDERR) 
W20160915-17:19:19.760(2)? (STDERR) Read more about installing npm peer dependencies:
W20160915-17:19:19.761(2)? (STDERR)   http://guide.meteor.com/using-packages.html#peer-npm-dependencies
W20160915-17:19:19.761(2)? (STDERR) 
W20160915-17:19:19.989(2)? (STDERR) /Users/ortiz/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20160915-17:19:19.989(2)? (STDERR)                         throw(ex);
W20160915-17:19:19.990(2)? (STDERR)                         ^
W20160915-17:19:19.990(2)? (STDERR) 
W20160915-17:19:19.990(2)? (STDERR) Error: Can't find npm module 'react-addons-transition-group'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
W20160915-17:19:19.991(2)? (STDERR)     at Object.Npm.require (/Users/ortiz/Siti/tutorial/meteor/react/flowrouter/.meteor/local/build/programs/server/boot.js:198:17)
W20160915-17:19:19.991(2)? (STDERR)     at options.fallback (packages/modules-runtime/modules-runtime.js:21:1)
W20160915-17:19:19.991(2)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:88:1)
W20160915-17:19:19.993(2)? (STDERR)     at meteorInstall.node_modules.meteor.react-runtime.react-runtime.js (packages/react-runtime/react-runtime.js:29:20)
W20160915-17:19:19.993(2)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160915-17:19:19.993(2)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160915-17:19:19.993(2)? (STDERR)     at /Users/ortiz/Siti/tutorial/meteor/react/flowrouter/.meteor/local/build/programs/server/packages/react-runtime.js:79:15
W20160915-17:19:19.994(2)? (STDERR)     at /Users/ortiz/Siti/tutorial/meteor/react/flowrouter/.meteor/local/build/programs/server/packages/react-runtime.js:92:3
W20160915-17:19:19.994(2)? (STDERR)     at /Users/ortiz/Siti/tutorial/meteor/react/flowrouter/.meteor/local/build/programs/server/boot.js:292:10
W20160915-17:19:19.995(2)? (STDERR)     at Array.forEach (native)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

**Comment by mattmacpherson** [comment]
Yeah I'm having the same issue. Can anyone comment on what is needed to make this work? I'm starting a new project so I can use an older version of react.

**Comment by samuelwight** [comment]
Getting the exact same error on the latest version of Meteor. Kinda sad that this is the supported router for Meteor and the team behind it still hasn't responded to this issue.

**Comment by ghost** [comment]
I ran the following code: `meteor show kadira:react-layout`
                                   
> With Meteor 1.3, use [react-mounter](https://github.com/kadirahq/react-mounter) instead of this.

Remove the kadira:react-layout and install react-mounter with npm. I tried and it works.

**Comment by rakibulalam** [comment]
install all required packages. Or use react mounter

**Comment by ghost** [comment]
Run meteor npm install
